## 1. 랜덤함수와 seed값 설정하기

#### seed값 설정하기
여러명이서 작업힐떼 렌담힌 값이 나오되, 동일한 랜덤한 값이 나오도록 지정하는 방법
보통은 한 번만 지정하면 계속해서 사용할 수 있다.  

시드값을 설정하지 않을때는 랜덤한 난수값이 어떤 기준으로 만들어질까?  
컴퓨터 시각을 기준으로 그때마다 다른 값을 도출하도록 알고리즘이 구현되어져 있다.  
시드값은 seed()함수안에 숫자를 넣음(음수는 못씀)으로써 수동으로 값을 만들어내는 알고리즘..  
seed(0)  
seed(100)  
seed(23)  
이때 seed()안에 넣는 정수가 동일하면 동일한 알고리즘이 돌기 때문에 같은 수의 난수를 지정받을 수 있다.


In [1]:
import numpy as np

In [10]:
np.random.seed(0)

In [3]:
arr1 = np.random.randn(4,4)
arr1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [4]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr3 = arr2.reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr4 = np.random.randint(10,20,16).reshape(4,4)
print(arr4)

arr4_1 = np.random.randint(10,size=9)
print(arr4_1)

[[15 10 13 13]
 [17 19 13 15]
 [12 14 17 16]
 [18 18 11 16]]
[7 7 8 1 5 9 8 9 4]


## 2. 인덱싱, 슬라이싱

In [7]:
narray = np.arange(5)
print(narray)

[0 1 2 3 4]


In [8]:
# 1.인덱싱과 슬라이싱으로 값 추출하기
print(narray[1],narray[-1]) # 인덱스에 음수가 붙으면 뒤에서 n번째로 이해
print(narray[1:])
print(narray[:])
print(narray)
print(narray[2:4])

1 4
[1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[2 3]


In [12]:
arr4

array([[15, 10, 13, 13],
       [17, 19, 13, 15],
       [12, 14, 17, 16],
       [18, 18, 11, 16]])

In [47]:
# 1) arr4의 첫번째 줄의 세번째 값
print(arr4[0,2])
print('-'*30)
# 2) arr4의 두번째 줄 다 가져오기
print(arr4[1]) # 1차원으로 가져오기
print(arr4[:1]) # 2차원으로 가져오기
print('-'*30)
# 3) arr4 전체 행에 대해서 4번재 열을 가져오기
print(arr4[:,-1]) # 1차원으로 가져오기
print(arr4[:,3:]) # 2차원으로 가져오기
print('-'*30)
# 4) arr4 전체 행에 대해서 1,2번째 열을 가지고 오려면
print(arr4[:,1:3])
print('-'*30)

13
------------------------------
[17 19 13 15]
[[15 10 13 13]]
------------------------------
[13 15 16 16]
[[13]
 [15]
 [16]
 [16]]
------------------------------
[[10 13]
 [19 13]
 [14 17]
 [18 11]]
------------------------------


## 3. 인덱싱과 조건 슬라이싱
---- 열거된 배열의 값에서 논리연산자 혹은 where 함수를 사용해서 내가 원하는 값을 가져올 수 있어야 한다.

In [56]:
arr2 = np.random.randn(4,4)


array([[ 1.86755896,  0.90604466, -0.86122569,  1.91006495],
       [-0.26800337,  0.8024564 ,  0.94725197, -0.15501009],
       [ 0.61407937,  0.92220667,  0.37642553, -1.09940079],
       [ 0.29823817,  1.3263859 , -0.69456786, -0.14963454]])

In [65]:
# 1. 논리연산자 사용
# arr2[arr2 < 0]
# arr2[arr2 > 0]

# 2. 0보다 작은값들(음수)은 전부 다 0으로 바꾸겠다.
arr2[arr2 < 0] = 0
print(arr2)
print('-'*30)

# 3. where 함수를 사용
arr2_w = np.where(arr2>0, arr2 , 0)
print(arr2_w)
print('-'*30)

[[1.86755896 0.90604466 0.         1.91006495]
 [0.         0.8024564  0.94725197 0.        ]
 [0.61407937 0.92220667 0.37642553 0.        ]
 [0.29823817 1.3263859  0.         0.        ]]
------------------------------
[[1.86755896 0.90604466 0.         1.91006495]
 [0.         0.8024564  0.94725197 0.        ]
 [0.61407937 0.92220667 0.37642553 0.        ]
 [0.29823817 1.3263859  0.         0.        ]]
------------------------------


In [66]:
### 중요
exama = np.array([[1,2],[3,4],[5,6]])
exama

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
# 2보다 큰값 추출
print(exama[exama>2])

[3 4 5 6]


## 4.Numpy 통계함수
---- sum(), min(), max(), mean(), argmax(), argmin(), cumsum()

In [74]:
arr4

array([[15, 10, 13, 13],
       [17, 19, 13, 15],
       [12, 14, 17, 16],
       [18, 18, 11, 16]])

In [77]:
np.sum(arr4,axis=0)

array([62, 61, 54, 60])

In [79]:
np.argmax(arr4,axis=0)

array([3, 1, 2, 2], dtype=int64)