### Numpy -> Numeric Python

In [5]:
import numpy as np

## 1. Numpy 배열과 리스트를 비교

#### 1. array() 함수 사용

In [17]:
myList = [4,5,6,7]
myArray = np.array(myList)
print(myList)
print(myArray)
'''
ndarray
다차원 행렬구조를 지원하는 Numpy의 핵심 클래스
넘파이배열은 ndarray클래스 타입으로 지원된다.
list - - - python
ndarray - - - Numpy

1차원 구조 --> vector
2차원 구조 --> matrix

'''
print(type(myList))
print(type(myArray))

[4, 5, 6, 7]
[4 5 6 7]
<class 'list'>
<class 'numpy.ndarray'>


In [21]:
myList_slice = myList[1:3] # 파이썬은 보통 카멜기법이 아니라 케밥기법
print(myList_slice)

myArray_slice = myArray[1:3] # 파이썬은 보통 카멜기법이 아니라 케밥기법
print(myArray_slice)

[5, 6]
[5 6]


In [22]:
myList_slice[0] = -5
myArray_slice[0] = -5
print(myList_slice, myArray_slice)

[-5, 6] [-5  6]


In [24]:
# 리스트와 ndarray의 차이점 정리
print(myList) # 안바뀜 -> 카피해서 새로운걸 만든다.
print(myArray) # 바뀜 -> 원본을 바로 바꿔 버린다. -> 메모리 효율성이 뛰어나다

[4, 5, 6, 7]
[ 4 -5  6  7]


#### 2. random() 함수 사용

In [43]:
a = np.random.rand(5) # 0 ~ 1 uniform distribution
print(a)
print(type(a))

[0.58271405 0.33136311 0.96102155 0.4351875  0.70444534]
<class 'numpy.ndarray'>


array([], shape=(0, 10, 5), dtype=float64)

In [58]:
np.random.rand(3,2)

array([[0.26994553, 0.47619605],
       [0.0131362 , 0.33237941],
       [0.1745366 , 0.27933534]])

In [98]:
np.random.randint(1,10,5)

array([8, 3, 4, 7, 5])

In [82]:
np.random.randn(10)

array([-0.3180202 ,  0.30216296, -0.2561871 ,  0.47296654, -0.33304834,
       -0.00471112, -0.08149999, -0.15052392,  2.2581052 , -0.03586144])

## 2. numpy배열의 초기화

In [ ]:
'''
초기화
배열의 생성함과 동시에 특정한 값을 할당(최초가 아님)

zeros()
ones()
arange()
rand()
'''


In [112]:
#1. zeros()
az = np.zeros(10)
print(az)
print(az.dtype)

#2. ones()
ao = np.ones(10)
print(ao)
print(ao.dtype)

#3. eye() 단위행렬 생성 
ee = np.eye(3) 
print(ee)
print(ee.dtype)

#4. arange()
print(np.arange(3,10,2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64
[3 5 7 9]


In [134]:
np.ones([3,3])*4

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [132]:
np.full([3,3],4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

## 3. 리스트와 np 배열의 차이점

In [ ]:
'''
리스트와 np배열의 차이점을 정리
--> 리스트는 서로다른 타입의 값들이 저장이 되는 반면에
numpy배열은 하나의 자료형만 저장할 수 있다.
이때 저장될때 특징을 가짐 -> 타입이 다르다면 더 큰 메모리를 가지는 타입으로 자동 캐스팅된다.


'''

In [146]:
narray_1 = np.array(L)
print(narray_1)
print(type(narray_1))

narray_2 = np.array(number)
print(narray_2)
print(type(narray_2))

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


In [165]:
#값의 타입을 명시해서 저장할 수도 있다. 이때 dtype 속성을 사용한다.
narray_3 = np.array(L,dtype='float')
print(narray_3)

[1. 2. 3. 4. 5.]


## 4. Numpy 배열의 속성
-------ndim, shape, reshape, size, type

In [167]:
a = np.zeros([3,3])

In [188]:
arr1 = np.array([[1.0,2,3],[4,5,6]]).astype('int')
arr1

# np의 함수를 이용해서
# 차원, 몇행몇열, 데이타가 총 몇개인지
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

print('-'*30)
print(arr1.dtype) # 값의 타입
print(type(arr1)) # 객체타입

print('-'*30)
# arr1배열 원소 값의 타입을 한번에 바꿀수 있다.
# 정수 -> 실수
arr1_1 = arr1.astype('float') # float default값 : float64
print(arr1_1)

print('-'*30)
arr2 = np.arange(32)
print(arr2)
arr2.reshape(8,4)

2
(2, 3)
6
------------------------------
int32
<class 'numpy.ndarray'>
------------------------------
[[1. 2. 3.]
 [4. 5. 6.]]
------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])